---
###############################################################################
# UniFi Legacy Install (Unifi Network Server / UniFi Controller)
###############################################################################
# Prepare system for install by creating user/group for service. Stopping
# service if enabled.

- name: 'Legacy | prep'
  ansible.builtin.import_tasks: 'prep.yml'

- name: 'Legacy | install'
  when: not _unifi_cfg_legacy_force_config_only_enable.raw
  ansible.builtin.import_tasks: 'install.yml'

- name: 'Legacy | config'
  ansible.builtin.import_tasks: 'config.yml'
