---
###############################################################################
# Default Unifi Version
###############################################################################
# A stripped down version of the meat-hook abortion that is the "easy
# installation scripts".
#
# Re-evaluate role when new version is release on newer dependencies to remove
# stretch installations.
#
# If unifi controller IP changes, ssh to each device to migrate to new IP:
#
#   set-inform http://{NEW IP}:8080/inform
#
# Reference:
# * https://community.ui.com/questions/UniFi-Installation-Scripts-or-UniFi-Easy-Update-Script-or-UniFi-Lets-Encrypt-or-UniFi-Easy-Encrypt-/ccbc7530-dd61-40a7-82ec-22b17f027776
# * https://devopstales.github.io/home/install-unifi-controller/
# * https://help.ui.com/hc/en-us/articles/220066768-UniFi-How-to-Install-and-Update-via-APT-on-Debian-or-Ubuntu
# * https://github.com/linuxserver/docker-unifi-controller/blob/master/Dockerfile

- name: 'install | package dependencies'
  ansible.builtin.apt:
    name:  '{{ unifi_default_dependencies }}'
    state: 'latest'
    update_cache: true

- name: 'install | add unifi repo key'
  ansible.builtin.apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id:        '06E85760C0A52C50'
    state:     'present'

- name: 'install | add unifi repo'
  ansible.builtin.apt_repository:
    repo:     'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti'
    filename: 'unifi'
    state:    'present'
    update_cache: true

# Unifi Controller requires MongoDB: 3.6. Install 3.6 from stretch.
- name: 'install | add mongodb 3.6 repo key'
  ansible.builtin.apt_key:
    url:   'https://www.mongodb.org/static/pgp/server-3.6.asc'
    state: 'present'

- name: 'install | add mongodb 3.6 repo'
  ansible.builtin.apt_repository:
    repo:     'deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main'
    filename: 'mongodb'
    state:    'present'
    update_cache: true

# Explicitly install from stretch to support mongo.
- name: 'install | add openjdk8 stretch repo'
  ansible.builtin.apt_repository:
    repo:     'deb http://deb.debian.org/debian stretch main'
    filename: 'openjdk-stretch'
    state:    'present'
    update_cache: true

# Set backup flag to prevent prompt if upgrading
# https://community.ui.com/questions/unifi-apt-get-upgrade-prompt-for-backups/f2ac7635-07f4-46fe-aeda-2933af474174
- name: 'install | enable auto upgrade'
  ansible.builtin.debconf:
    name:     'unifi'
    question: 'unifi/has_backup'
    value:    '{{ unifi_backup|string|lower }} }}'
    vtype:    'boolean'

- name: 'install | install unifi'
  ansible.builtin.apt:
    name:  '{{ unifi_default_packages }}'
    state: 'latest'
    update_cache: true
  notify: 'restart unifi'
