---
###############################################################################
# Unifi Handlers
###############################################################################

- name: 'restart unifi'
  ansible.builtin.systemd:
    name:    'unifi'
    enabled: true
    state:   'restarted'
